name: Repo Admin
on:
  push:
    branches: [ main ]
    paths:
      - doc/*
      - src/*/*.scala
jobs:
  admin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Tidy repository
      uses: propensive/tumult@0.5.4
    - name: Autocommit changes
      uses: stefanzweifel/git-auto-commit-action@v4
